# Filename: .appveyor.yml

platform:
    - x86
    - x64

image:
    - Visual Studio 2015
    - Visual Studio 2017

install:
    - git submodule update --init

build_script:
    - ps: .\script\appveyor.ps1
